# Análisis de Componentes Principales - Paso a Paso

**El objetivo es reducir el numero de variables para reducir los cuellos de botella. Cuando tengamos un algoritmo muy lento o muchisimos datos, este analisis de componentes principales sera la mejor opcion.**

**Notitas**
1. Lo primero que debo preguntar es como de pequeño puedo lograr hacer el dataset.
    * Esto dependera naturalmente de cada dataset

======================================================================================

* Estandarizar los datos (para cada una de las m observaciones)

* Obtener los vectores y valores propios a partir de la matriz de covarianzas o de correlaciones o incluso la técnica de singular vector decomposition.

* Ordenar los valores propios en orden descendente y quedarnos con los *p* que se correpondan a los *p mayores* y así disminuir el número de variables del dataset (p<m)

* Constrir la matriz de proyección W a partir de los p vectores propios

* Transformar el dataset original X a través de W para así obtener dadtos en el subespacio dimensional de dimensión p, que será Y

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv("../datasets/iris/iris.csv")

In [39]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
X = df.iloc[:,0:4].values #me quedo con todas las filas desde la 0 hasta la 4
y = df.iloc[:,4].values #todas las filas solo de la columna 4

In [41]:
X #filas se guardan en formato array

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [42]:
import chart_studio
import plotly.graph_objects as go

Vamos a crear un histograma para cada una de las variables

**NOTA SOBRE PLOTLY Y CHART STUDIO**

Chart estudio, antiguamente Plotly es ahora de pago. En su reemplazo esta Chart Studio. Al igual que su hermanito de pago necesitamos un usuario y contraseña para poder acceder a la API
 Puedes consultar tu key aqui:
https://chart-studio.plot.ly/settings/profile

_(esta ya se reinicio, no te preocupes) asi que deberas actualizar esta clave para generar de nuevo el grafico_

In [85]:
chart_studio.tools.set_credentials_file(username='luisbenitez02', api_key='tUoPGqOMj7r2RXDYKQMC')

In [91]:
traces = []
legend = {0:True, 1:True, 2:True, 3:True}

colors = {'setosa': 'rgb(255,127,20)',
         'versicolor': 'rgb(31, 220, 120)',
         'virginica': 'rgb(44, 50, 180)'}

for col in range(4): 
    for key in colors:
        traces.append(go.Histogram(x=X[y==key, col], opacity = 0.7, 
                                xaxis="x%s"%(col+1), marker=go.Marker(color=colors[key]),
                               name = key, showlegend=legend[col]))
    legend = {0:False, 1:False, 2:False, 3:False}   
data = go.Data(traces)
layout = go.Layout(barmode="overlay", 
                xaxis=go.layout.XAxis(domain=[0,0.25], title="Long. Sépalos (cm)"),
                xaxis2=go.layout.XAxis(domain=[0.3, 0.5], title = "Anch. Sépalos (cm)"),
                xaxis3=go.layout.XAxis(domain = [0.55, 0.75], title = "Long. Pétalos (cm)"),
                xaxis4=go.layout.XAxis(domain=[0.8,1.0], title = "Anch. Pétalos (cm)"),
                yaxis=go.layout.YAxis(title="Número de ejemplares"),
                title="Distribución de los rasgos de las diferentes flores Iris")

fig = go.Figure(data = data, layout = layout)
chart_studio.plotly.iplot(fig)
#fig.show()

#### **NOTA IMPORTANTE**
El grafico se muestra en una ventana del navegador en nuestr acuenta de Chart studio
**Es un grafico muy bonito**

https://plot.ly/~luisbenitez02/7.embed

![Grafico Generado](../Recursos/imgs/Plot.PNG)

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
X_std = StandardScaler().fit_transform(X)
X_std

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

## 1- Calculamos la descomposición de valores y vectores propios

### a) Usando la Matriz de Covarianzas

Este es el enfoque mas clasico de ACP

In [53]:
from IPython.display import display, Math, Latex

In [54]:
display(Math(r'\sigma_{jk} = \frac{1}{n-1}\sum_{i=1}^m (x_{ij} - \overline{x_j})(x_{ik} - \overline{x_k})'))

<IPython.core.display.Math object>

In [55]:
display(Math(r'\Sigma = \frac{1}{n-1}((X-\overline{x})^T(X-\overline{x}))'))

<IPython.core.display.Math object>

In [56]:
display(Math(r'\overline{x} = \sum_{i=1}^n x_i\in \mathbb R^m'))

<IPython.core.display.Math object>

In [58]:
import numpy as np

In [61]:
mean_vect = np.mean(X_std, axis=0)
mean_vect #devuelve la media o promedio de las 4 varaibles

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [63]:
cov_matrix = (X_std - mean_vect).T.dot((X_std - mean_vect))/(X_std.shape[0]-1)
print("La matriz de covarianzas es \n%s"%cov_matrix)
#sabemos que esta bien por que en el centro o la diagonal tenemos siempre 1's

La matriz de covarianzas es 
[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]


**¿Por que no salen puros 1's exactos en la matriz de covarianza?**
* Por que vengo arrastrando rendondeos y trabajo con numeros cercanos a 0
* la covarianza no necesariamente tiene que dar 1 en la diagonal

In [64]:
np.cov(X_std.T) #covarianza

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [66]:
eig_vals, eig_vectors = np.linalg.eig(cov_matrix) #valores propios y vectores propios de la matriz
print("Valores propios \n%s"%eig_vals)
print("Vectores propios \n%s"%eig_vectors)

Valores propios 
[2.93808505 0.9201649  0.14774182 0.02085386]
Vectores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


### b) Usando la Matriz de Correlaciones

Es muy tipico usar las correlaciones en lugar de las covarianzas en el campo de las finanzas

In [67]:
corr_matrix = np.corrcoef(X_std.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

La diagonal tiene 1, ya no tenemos errores de redondeo

In [68]:
eig_vals_corr, eig_vectors_corr = np.linalg.eig(corr_matrix)
print("Valores propios \n%s"%eig_vals_corr)
print("Vectores propios \n%s"%eig_vectors_corr)

Valores propios 
[2.91849782 0.91403047 0.14675688 0.02071484]
Vectores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [69]:
corr_matrix = np.corrcoef(X.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

### c) Singular Value Decomposition

Esta tecnica mejora muchisimo la eficacia computacional

In [71]:
u,s,v = np.linalg.svd(X_std.T)
u

array([[-0.52106591, -0.37741762,  0.71956635,  0.26128628],
       [ 0.26934744, -0.92329566, -0.24438178, -0.12350962],
       [-0.5804131 , -0.02449161, -0.14212637, -0.80144925],
       [-0.56485654, -0.06694199, -0.63427274,  0.52359713]])

In [72]:
s

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [73]:
v

array([[ 1.08239531e-01,  9.94577561e-02,  1.12996303e-01, ...,
        -7.27030413e-02, -6.56112167e-02, -4.59137323e-02],
       [-4.09957970e-02,  5.75731483e-02,  2.92000319e-02, ...,
        -2.29793601e-02, -8.63643414e-02,  2.07800179e-03],
       [ 2.72186462e-02,  5.00034005e-02, -9.42089147e-03, ...,
        -3.84023516e-02, -1.98939364e-01, -1.12588405e-01],
       ...,
       [ 5.43380310e-02,  5.12936114e-03,  2.75184277e-02, ...,
         9.89532683e-01, -1.41206665e-02, -8.30595907e-04],
       [ 1.96438400e-03,  8.48544595e-02,  1.78604309e-01, ...,
        -1.25488246e-02,  9.52049996e-01, -2.19201906e-02],
       [ 2.46978090e-03,  5.83496936e-03,  1.49419118e-01, ...,
        -7.17729676e-04, -2.32048811e-02,  9.77300244e-01]])

## 2 - Las componentes principales

In [75]:
for ev in eig_vectors:
    print("La longitud del VP es: %s"%np.linalg.norm(ev))

La longitud del VP es: 0.9999999999999999
La longitud del VP es: 1.0
La longitud del VP es: 0.9999999999999999
La longitud del VP es: 1.0


haremos un rating de los valores propios desde el mas alto hasta el mas bajo, eliminaremos los que menos informacion tengan

In [76]:
eigen_pairs = [(np.abs(eig_vals[i]), eig_vectors[:,i]) for i in range(len(eig_vals))]
eigen_pairs

[(2.938085050199995,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624871,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.14774182104494812,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.020853862176462873,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

Ordenamos los vectores propios con valor propio de mayor a menor

In [77]:
eigen_pairs.sort()
eigen_pairs.reverse()
eigen_pairs

[(2.938085050199995,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624871,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.14774182104494812,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.020853862176462873,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

In [78]:
print("Valores propios en orden descendente:")
for ep in eigen_pairs:
    print(ep[0])

Valores propios en orden descendente:
2.938085050199995
0.9201649041624871
0.14774182104494812
0.020853862176462873


In [79]:
total_sum = sum(eig_vals)
var_exp = [(i/total_sum)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

In [89]:
plot1 = Bar(x=["CP %s"%i for i in range(1,5)], y = var_exp, showlegend=False)
plot2 = go.Scatter(x=["CP %s"%i for i in range(1,5)], y = cum_var_exp, showlegend=True, name = "% de Varianza Explicada Acumulada")

data = go.Data([plot1, plot2])

layout = Layout(xaxis = XAxis(title="Componentes principales"), 
               yaxis = YAxis(title = "Porcentaje de varianza explicada"),
               title = "Porcentaje de variabilidad explicada por cada componente principal")

fig = Figure(data = data, layout = layout)
py.iplot(fig)

In [92]:
W = np.hstack((eigen_pairs[0][1].reshape(4,1), 
               eigen_pairs[1][1].reshape(4,1)))
W

array([[ 0.52106591, -0.37741762],
       [-0.26934744, -0.92329566],
       [ 0.5804131 , -0.02449161],
       [ 0.56485654, -0.06694199]])

In [93]:
X[0]

array([5.1, 3.5, 1.4, 0.2])