# El método de k-means

In [1]:
import numpy as np

In [4]:
data = np.random.random(90).reshape(30,3)#parto los datos en 3 columnas de 30 elementos cada una
data

array([[0.69777057, 0.08453919, 0.07589744],
       [0.74220236, 0.06276195, 0.08988476],
       [0.96216856, 0.79658425, 0.69518975],
       [0.63992902, 0.17870581, 0.85345951],
       [0.57180065, 0.57336641, 0.31326213],
       [0.5003835 , 0.81981326, 0.60880847],
       [0.88628009, 0.01910656, 0.10283429],
       [0.99262054, 0.69073346, 0.87725356],
       [0.06738178, 0.06053023, 0.12035304],
       [0.84026175, 0.78211347, 0.69673602],
       [0.15413707, 0.11957605, 0.58954523],
       [0.45629752, 0.9993395 , 0.10040487],
       [0.2785607 , 0.22079731, 0.88127673],
       [0.90900795, 0.28913804, 0.4939249 ],
       [0.58190442, 0.04887616, 0.26937736],
       [0.43944972, 0.84267414, 0.89792382],
       [0.74039119, 0.99101875, 0.3118175 ],
       [0.50522498, 0.46925504, 0.42977371],
       [0.12505461, 0.74163306, 0.6927741 ],
       [0.7142318 , 0.93404112, 0.55021724],
       [0.12540173, 0.31426058, 0.97793045],
       [0.09060562, 0.43045904, 0.52500059],
       [0.

K-Means tiene la particularidad de tener que especificar cuantos Clusters queremos antes de empezar

In [7]:
c1 = np.random.choice(range(len(data)))#para elegir nuestro centrodiode, como no sabemso cual lo hacemos aleatorio
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.09060562, 0.43045904, 0.52500059],
       [0.72959913, 0.80633358, 0.28857386]])

In [8]:
from scipy.cluster.vq import vq

In [9]:
vq(data,clust_centers)

(array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1]),
 array([0.7531477 , 0.76976293, 0.46852969, 0.68776534, 0.28245986,
        0.39404531, 0.82387772, 0.65504766, 0.54874977, 0.42359081,
        0.32380625, 0.38386537, 0.45411215, 0.58467751, 0.67254981,
        0.65626613, 0.18645468, 0.42717971, 0.35519566, 0.2915521 ,
        0.46889051, 0.        , 0.23621879, 0.64323925, 0.41177209,
        0.        , 0.30429312, 0.46769283, 0.5241905 , 0.20971294]))

In [10]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers)#entrega informacion de varicentros
#numero final es es valor de la suma de los cuadrados

(array([[0.31263895, 0.37589365, 0.57641815],
        [0.74586586, 0.61193878, 0.4058028 ]]), 0.4131267290758688)

In [12]:
kmeans(data,2)

(array([[0.43271119, 0.22706805, 0.41862765],
        [0.60864045, 0.78202518, 0.58613479]]), 0.3845477863678973)